apiVersion: apps/v1

kind: Deployment

metadata:
  name: clouddeployx-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: clouddeployx

  template:

    metadata:
      labels:
        app: clouddeployx

    spec:
      containers:
        - name: clouddeployx-container
          image: clouddeployx:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: clouddeployx-config
            - secretRef:
                name: clouddeployx-secret

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"