name: CloudDeployX CI

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: clouddeployx

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login To Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:latest .
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag Image For ECR
        run: |
          docker tag $ECR_REPOSITORY:latest \
          265411104260.dkr.ecr.ap-south-1.amazonaws.com/clouddeployx:latest

          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          265411104260.dkr.ecr.ap-south-1.amazonaws.com/clouddeployx:$IMAGE_TAG

      - name: Push Image To ECR
        run: |
          docker push 265411104260.dkr.ecr.ap-south-1.amazonaws.com/clouddeployx:latest

          docker push 265411104260.dkr.ecr.ap-south-1.amazonaws.com/clouddeployx:$IMAGE_TAG